GET http://localhost:8080/users/posts HTTP/1.1

###
GET http://localhost:8080/users/posts/863bb7ff-8d71-424c-a0fd-6331b58921c7 HTTP/1.1


###
POST http://localhost:8080/users/posts HTTP/1.1
Content-Type: application/json

{
    "title" : "annonce",
    "content" :"blabla",
    "localisation" : "dax",
    "language" : "anglais",
    "UserId" : "0aed7098-4979-4256-9b9d-534764103fc4"
}

###

PUT http://localhost:8080/users/posts/2f2ad705-e901-4702-a122-da890e3327fe HTTP/1.1
Content-Type: application/json

{
    "title" : "annonce2",
    "content" :"blablabla54",
    "localisation" : "biarritz",
    "language" : "french"
}

###

DELETE http://localhost:8080/users/posts/c5e5dca9-00c5-405f-8146-ca97da2c0c97 HTTP/1.1