GET http://localhost:8080/users/userTypes HTTP/1.1

### 
GET http://localhost:8080/users/userTypes/b64ece64-4a8b-4fb2-8d35-b88c3bb813b3 HTTP/1.1
###
POST http://localhost:8080/users/userTypes HTTP/1.1
Content-Type: application/json

{
    "label" : "Entreprise"
}

###
PUT http://localhost:8080/users/userTypes/d7211e0f-fb8d-487f-949f-aff1ae5eab87 HTTP/1.1
Content-Type: application/json


{
    "label" :"Etudiant poil aux dents"
}


###
DELETE http://localhost:8080/users/userTypes/d7211e0f-fb8d-487f-949f-aff1ae5eab87 HTTP/1.1