### GET ALL FAQ
GET http://localhost:8080/activityField HTTP/1.1

###GET one FAQ
GET http://localhost:8080/activityField/44b6733d-a728-411e-912e-36ba03cc0967  HTTP/1.1

### POST new FAQ
POST  http://localhost:8080/activityField HTTP/1.1
Content-Type: application/json

{
    "labelFr": "Bâtiment",
    "labelEs": "Building",
    "labelEus": "Eraikin"
}

### PUT one FAQ
PUT http://localhost:8080/activityField/c0e99f6e-d410-44da-84fe-434ce76e9068 HTTP/1.1
Content-Type: application/json

{
    "labelFr": "Informatique",
    "labelEs": "Data processing",
    "labelEus": "Informatika"
}

### Delete FAQ 
DELETE http://localhost:8080/activityField/44b6733d-a728-411e-912e-36ba03cc0967  HTTP/1.1
