GET http://localhost:8080/api/v1/partners HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExYjM5OTM1LTQwNmItNGE1NC1hNDk5LWJhNzAxODhiMGFiNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NDIxNTI3NSwiZXhwIjoxNTk0MzAxNjc1fQ.7-UtY6-5hr7_if0x0Ia7fQIIScxoRqM5wUE5THSYh8Q

###
GET http://localhost:8080/api/v1/partners/e995f399-172e-40a8-8d53-92da0b2e480b HTTP/1.1


###
POST http://localhost:8080/api/v1/partners HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExYjM5OTM1LTQwNmItNGE1NC1hNDk5LWJhNzAxODhiMGFiNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NDIxNTI3NSwiZXhwIjoxNTk0MzAxNjc1fQ.7-UtY6-5hr7_if0x0Ia7fQIIScxoRqM5wUE5THSYh8Q
Content-Type: application/json

{
    "label" : "entreprise 1",
    "url" : "entreprise1@dev.fr",
    "description" : "hello world1",
    "logo" : "https://via.placeholder.com/150",
    "favorite" : true
}

###

PUT http://localhost:8080/api/v1/partners/e72f7c3a-c2a4-4468-9e02-d7be8358886e HTTP/1.1
Content-Type: application/json

{
    "label" : "annonce2"
}

###

DELETE http://localhost:8080/api/v1/partners/e72f7c3a-c2a4-4468-9e02-d7be8358886e HTTP/1.1