GET http://localhost:8080/api/v1/posts HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlNTQwYTE0LTliYmItNGFhNi1hZDUyLTY3NWJiOWVkNzM4ZCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NDI5OTQ3MSwiZXhwIjoxNTk0Mzg1ODcxfQ._LskOOKVEGDwqBwa813cQIhRo2OzX0GBNBQLn2OMJPY
###
GET http://localhost:8080/api/v1/posts/20a6d5a2-e2e4-42d3-b681-0b810d3ecaf0 HTTP/1.1


###
POST http://localhost:8080/api/v1/posts HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlNTQwYTE0LTliYmItNGFhNi1hZDUyLTY3NWJiOWVkNzM4ZCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NDI5OTQ3MSwiZXhwIjoxNTk0Mzg1ODcxfQ._LskOOKVEGDwqBwa813cQIhRo2OzX0GBNBQLn2OMJPY
Content-Type: application/json

{
    "title" : "annonce5",
    "content" :"blablabla54",
    "localisation" : "biarritz",
    "language" : "french",
    "UserId": "da41cd98-54f2-4aa8-a6af-8d94dbed89c0",
    "TypePostId": "a7e93a07-804a-4745-846e-a3ef4af6a002",
    "JobCategoryId": "3097ce0e-20e0-4f40-8b45-c6974cd4d671"
}

###

PUT http://localhost:8080/api/v1/posts/2f2ad705-e901-4702-a122-da890e3327fe HTTP/1.1
Content-Type: application/json

{
    "title" : "annonce2",
    "content" :"blablabla54",
    "localisation" : "biarritz",
    "language" : "french"
}

###

DELETE http://localhost:8080/api/v1/posts/56c534b4-a47f-4621-86c2-33d41a812c90 HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjY2QwOWNiLTM4NDQtNDNiZS04OTQzLTc1NzhlYjI3ZDY3YSIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5Mzg5NTc1NiwiZXhwIjoxNTkzOTgyMTU2fQ.72NxYJV0stBwBp8af-GfzLl57Qf9F4K3Q9bkCUkCk8U
