GET http://localhost:8080/api/v1/replies HTTP/1.1

###Post an apply

POST http://localhost:8080/api/v1/replies/apply HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3YWNkOTkxLWI2ZGItNGM1MC05NDA4LTIyYTAzZGFlN2MwNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTg0MDA0MywiZXhwIjoxNTk1OTI2NDQzfQ.60rx9f5d0VoWFZhWtWKX0dJBDsGRQOtJ1N9jnlxQmeI
Content-Type: application/json

{
    "title" : "hello",
    "comment" : "votre annonce m'interesse.",
    "resume" : "https://via.placeholder.com/150",
    "UserId" : "15000946-f746-4d5a-b458-4ea3cd7ca2a6",
    "PostId" : "2dc9034a-9697-48ad-8f1e-ded51206c138",
    "userPostId" :"013eb59f-644f-4628-96ac-1945dbb0a757",
    "titlePost" : "recherche secretaire"
}