### Get all the post types
GET http://localhost:8080/api/v1/postTypes HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3YWNkOTkxLWI2ZGItNGM1MC05NDA4LTIyYTAzZGFlN2MwNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTg0MDA0MywiZXhwIjoxNTk1OTI2NDQzfQ.60rx9f5d0VoWFZhWtWKX0dJBDsGRQOtJ1N9jnlxQmeI


### Get one post type
GET http://localhost:8080/api/v1/postTypes/2464b82e-838f-4199-9fef-c5446756f6d5 HTTP/1.1

### Post one post type
POST http://localhost:8080/api/v1/postTypes HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3YWNkOTkxLWI2ZGItNGM1MC05NDA4LTIyYTAzZGFlN2MwNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTg0MDA0MywiZXhwIjoxNTk1OTI2NDQzfQ.60rx9f5d0VoWFZhWtWKX0dJBDsGRQOtJ1N9jnlxQmeI
Content-Type: application/json

{
    "labelFr" : "partenariat",
    "labelEs" : "partenarias",
    "labelEus" : "partenariak"
}

### Put one post type
PUT http://localhost:8080/api/v1/postTypes/9db9cfc4-4304-408d-9e20-a24c13d47ee0 HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3YWNkOTkxLWI2ZGItNGM1MC05NDA4LTIyYTAzZGFlN2MwNCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTg0MDA0MywiZXhwIjoxNTk1OTI2NDQzfQ.60rx9f5d0VoWFZhWtWKX0dJBDsGRQOtJ1N9jnlxQmeI
Content-Type: application/json


{
    "labelFr" : "recherche & dev",
    "labelEs" : "buscas & dev",
    "labelEus" : "recherch & dev"
}

### Delet one post type
DELETE http://localhost:8080/api/v1/postTypes/e0cc6580-3268-4168-a434-ad62583634ec  HTTP/1.1
