
#### get all users
GET http://localhost:8080/api/v1/users HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhZjczMjBhLTViMjEtNDE4Ni1hZjdkLTc2NTc4Y2JlZjEyMCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTgzNzQwMiwiZXhwIjoxNTk1OTIzODAyfQ.4jeNQPIDpusnHDI6OghLn31cmaFpkWvyO49Hw9Wc1EU

#### get one user

GET http://localhost:8080/api/v1/users/0d5d2399-b231-40eb-ade8-9b65d7f3d1c2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhZjczMjBhLTViMjEtNDE4Ni1hZjdkLTc2NTc4Y2JlZjEyMCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTgzNjQ3OSwiZXhwIjoxNTk1OTIyODc5fQ.GOJm2waNxTAhkLjPHnanq3IZoAS9UANjQAM76kJO8lg

###
POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "lastName" : "maxime",
    "firstName" : "reloue",
    "email" : "reloue@je.fr",
    "password" : "reloue2",
    "localisation" : "vielle",
    "country": "France",
    "phone_number" : 556325365,
    "phone_number2" : 558547854,
    "schoolName" : "wcs",
    "companyName" : "wcs",
    "siret" : "211680374",
    "qualification" : "job",
    "mobility" : "france",
    "name_organisation" : "wcs",
    "isActive" : false,
    "logo" : "bjisdckjs",
    "ActivityFieldId" : "07dac2cd-63d1-4b3f-9795-db9ee36f37a3",
    "UserTypeId" : "6f73feb0-2e71-48c9-8077-686717f005e0",
    
}



###Auth Admin
POST http://localhost:8080/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "admin@dev.com",
    "password" : "admin"
}

###register
POST http://localhost:8080/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "lastName" : "Dertone",
    "firstName" : "Paul",
    "email" : "p.dertone@gmail.com",
    "password" : "toto",
    "localisation" : "vielle",
    "country": "Espagne",
    "phone_number" : "0656565656",
    "phone_number2" : "558547854",
    "schoolName" : "wcs",
    "companyName" : "wcs",
    "siret" : "211680374",
    "qualification" : "job",
    "mobility" : "Espagne",
    "name_organisation" : "wcs",
    "isActive" : false,
    "logo" : "bjisdckjs",
    "RoleId" : "a5be2e09-9eb6-4212-88c4-caa5af81abe6",
    "UserTypeId" : "b59a0dfc-8f2c-4b12-82cc-d904007c8d55"
}

###

PUT http://localhost:8080/api/v1/users/0d5d2399-b231-40eb-ade8-9b65d7f3d1c2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhZjczMjBhLTViMjEtNDE4Ni1hZjdkLTc2NTc4Y2JlZjEyMCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTgzNjQ3OSwiZXhwIjoxNTk1OTIyODc5fQ.GOJm2waNxTAhkLjPHnanq3IZoAS9UANjQAM76kJO8lg

{
    "lastName" : "Moulon",
    "firstName" : "Marylou",
    "email" : "helloworldtest@put.com"
}

###

DELETE http://localhost:8080/api/v1/users/e2ded431-0f6c-4726-a35f-89e5b262d743 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhZjczMjBhLTViMjEtNDE4Ni1hZjdkLTc2NTc4Y2JlZjEyMCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTgzNjQ3OSwiZXhwIjoxNTk1OTIyODc5fQ.GOJm2waNxTAhkLjPHnanq3IZoAS9UANjQAM76kJO8lg

###
GET http://localhost:8080/api/v1/users/445ee66c-b868-46e2-8154-f0e40a0a43dd/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhZjczMjBhLTViMjEtNDE4Ni1hZjdkLTc2NTc4Y2JlZjEyMCIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NTgzNjQ3OSwiZXhwIjoxNTk1OTIyODc5fQ.GOJm2waNxTAhkLjPHnanq3IZoAS9UANjQAM76kJO8lg
