GET http://localhost:8080/api/v1/users HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MGMxNGMyLTIyNmEtNDU0YS1hODkwLTI5MDRiZThlODEwOSIsImVtYWlsIjoiYWRtaW5AZGV2LmNvbSIsInJvbGUiOiJBRE1JTiIsInR5cGUiOm51bGwsImlhdCI6MTU5NDA1NzU5MCwiZXhwIjoxNTk0MTQzOTkwfQ.hGBnMgCTWAo48Vdyft_1EievAAdhlOQMX-748v68Wu8

####

GET http://localhost:8080/api/v1/users/165162305 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4YzQyNjU4LTNlMjctNGMxYy04YjgzLWNlZTRjYWQ3MWUyNyIsImVtYWlsIjoidXNlckBkZXYuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTM2Nzg2MzIsImV4cCI6MTU5Mzc2NTAzMn0.rccNCXbw84slUi1RLu0756KpyHogf6Cf-qoxEIsc6i4

###
POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "lastName" : "maxime",
    "firstName" : "reloue",
    "email" : "reloue@je.fr",
    "password" : "reloue2",
    "localisation" : "vielle",
    "country": "France",
    "phone_number" : 556325365,
    "phone_number2" : 558547854,
    "schoolName" : "wcs",
    "companyName" : "wcs",
    "siret" : "211680374",
    "qualification" : "job",
    "mobility" : "france",
    "name_organisation" : "wcs",
    "isActive" : false,
    "logo" : "bjisdckjs",
    "ActivityFieldId" : "07dac2cd-63d1-4b3f-9795-db9ee36f37a3",
    "UserTypeId" : "6f73feb0-2e71-48c9-8077-686717f005e0",
    
}


###

PUT http://localhost:8080/api/v1/users/d85df18b-9722-4e65-a41c-c21e4f5a0735 HTTP/1.1
Content-Type: application/json

{
    "lastName" : "Nicolas",
    "firstName" : "Pierre",
    "email" : "helloworld",
    "password" : "blablabla",
    "localisation" : "anglet",
    "country": "France",
    "phone_number" : 10940239,
    "phone_number2" : 58493029,
    "isAdmin" : false,
    "schoolName" : "HEC",
    "companyName" : "HEC",
    "siret" : "234536251",
    "qualification" : "metier",
    "mobility" : "USA",
    "name_organisation" : "ADIE",
    "isActive" : false,
    "logo" : "mlkdmlqksml.png"
}

###

DELETE http://localhost:8080/api/v1/users/c5e5dca9-00c5-405f-8146-ca97da2c0c97 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4YzQyNjU4LTNlMjctNGMxYy04YjgzLWNlZTRjYWQ3MWUyNyIsImVtYWlsIjoidXNlckBkZXYuY29tIiwicm9sZSI6IlVTRVIiLCJ0eXBlIjpudWxsLCJpYXQiOjE1OTM2Nzk1NDV9.dUFgcCnGmTQZW3dcfRxq2ErNqXvNOI4jC19HVk2J710

###
GET http://localhost:8080/api/v1/users/05f78664-b0e1-43bf-b6bc-ad7312cdbdd5/posts HTTP/1.1