GET http://localhost:8080/api/v1/users HTTP/1.1

####

GET http://localhost:8080/api/v1/users/b936fa4e-c26a-4bb0-8013-094da84b35f2 HTTP/1.1


###
POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "lastName" : "Nicolas",
    "firstName" : "Pierre",
    "email" : "hello",
    "password" : "hellohe",
    "localisation" : "vielle",
    "phone_number" : 556325365,
    "phone_number2" : 558547854,
    "isAdmin" : true,
    "schoolName" : "wcs",
    "companyName" : "wcs",
    "siret" : "211680374",
    "qualification" : "job",
    "mobility" : "france",
    "name_organisation" : "wcs",
    "isActive" : false,
    "logo" : "bjisdckjs",
    "ActivityFieldId" : "c58c9548-2361-4954-8e85-a32171dd757d",
    "UserTypeId" : "332ed989-8117-4e7f-930a-9bda7b7e9c10"
}

###

PUT http://localhost:8080/api/v1/users/d85df18b-9722-4e65-a41c-c21e4f5a0735 HTTP/1.1
Content-Type: application/json

{
    "lastName" : "Nicolas",
    "firstName" : "Pierre",
    "email" : "helloworld",
    "password" : "blablabla",
    "localisation" : "anglet",
    "phone_number" : 10940239,
    "phone_number2" : 58493029,
    "isAdmin" : false,
    "schoolName" : "HEC",
    "companyName" : "HEC",
    "siret" : "234536251",
    "qualification" : "metier",
    "mobility" : "USA",
    "name_organisation" : "ADIE",
    "isActive" : false,
    "logo" : "mlkdmlqksml.png"
}

###

DELETE http://localhost:8080/api/v1/users/c5e5dca9-00c5-405f-8146-ca97da2c0c97 HTTP/1.1

###
GET http://localhost:8080/api/v1/users/05f78664-b0e1-43bf-b6bc-ad7312cdbdd5/posts HTTP/1.1